# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PW5iB12Xcd_PCvFTHQ_XAeEv7OV4jweA
"""

print("hello World")

for i in range(0,100):
  print(i)